import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export async function generateTicketsPDF(tickets: any[], fromDate: string, toDate: string) {
  const doc = new jsPDF();
  
  try {
    const response = await fetch('/cypadi%20trancyparent%20logo.png');
    if (response.ok) {
      const blob = await response.blob();
      const base64data = await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as string);
        reader.readAsDataURL(blob);
      });
      // Add logo to PDF (x, y, width, height)
      doc.addImage(base64data, 'PNG', 14, 15, 50, 20); 
    } else {
      // Fallback text if logo fails to load
      doc.setFontSize(22);
      doc.setTextColor(219, 39, 119); 
      doc.text("CYPADI", 14, 25);
    }
  } catch (error) {
    console.error("Failed to load logo", error);
    doc.setFontSize(22);
    doc.setTextColor(219, 39, 119); 
    doc.text("CYPADI", 14, 25);
  }
  
  doc.setFontSize(16);
  doc.setTextColor(40, 40, 40);
  doc.text("IT Support Tickets Report", 14, 45);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by: AVISA System`, 14, 55);
  doc.text(`Prepared by: System Administrator`, 14, 60);
  doc.text(`Date Range: ${fromDate} to ${toDate}`, 14, 65);
  
  const tableData = tickets.map(t => [
    t.ticketNumber,
    t.title,
    t.status,
    t.priority,
    t.user?.name || 'Unknown',
    new Date(t.createdAt).toLocaleDateString()
  ]);

  autoTable(doc, {
    startY: 75,
    head: [['ID', 'Title', 'Status', 'Priority', 'Submitter', 'Date']],
    body: tableData,
    headStyles: { fillColor: [219, 39, 119] },
  });

  doc.save(`CYPADI_Tickets_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}

export function generateTicketsCSV(tickets: any[]) {
  const headers = ['ID', 'Title', 'Status', 'Priority', 'Submitter', 'Date'];
  
  const rows = tickets.map(t => [
    t.ticketNumber,
    `"${t.title.replace(/"/g, '""')}"`, // Escape quotes for CSV
    t.status,
    t.priority,
    `"${t.user?.name || 'Unknown'}"`,
    new Date(t.createdAt).toLocaleDateString()
  ]);
  
  const csvContent = "data:text/csv;charset=utf-8," + 
    [headers.join(","), ...rows.map(e => e.join(","))].join("\n");
    
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", `CYPADI_Tickets_Report_${new Date().toISOString().split('T')[0]}.csv`);
  document.body.appendChild(link); // Required for Firefox
  link.click();
  document.body.removeChild(link);
}
